from os import getenv

CONSUMER_KEY = getenv('CONSUMER_KEY')
CONSUMER_SECRET = getenv('CONSUMER_SECRET')
ACCESS_TOKEN = getenv('ACCESS_TOKEN')
ACCESS_SECRET = getenv('ACCESS_SECRET')
# secs
CACHE_TIMER = int(getenv('CACHE_TIMER'))
# mins
CONSUME_INTERVAL = int(getenv('CONSUME_INTERVAL'))
BOOTSTRAP_SERVE_LOCAL = True
